### ISSUE TITLE
Need to determine tagging story wrt CLI version

### ISSUE THREAD

**Issue by chrsmith** [pulumi/actions#10]
The container currently downloads a specific version of the CLI. However, this version will enviably get out of date as newer versions of Pulumi are released.

However, if we always have the container pull the "latest", then it leaves developers who require a specific CLI version (e.g. to prevent any breaking library changes).

So I think we need to update this package to automatically push new container versions for every release of the CLI? e.g. `pulumi/actions:latest`, `pulumi/actions:v0.16.16`, etc. @ellismg does that sound like the right solution?

**Comment by andy9775** [comment]
Makes sense. 

The flow could also be automated. Each time a new pulumi version is released, it can auto-build the latest version and tag `:latest` but also tag it `:v<version>` then push out.

**Comment by chrsmith** [comment]
Looking into this a bit more, it seems like the right solution here is to move the `Dockerfile` and specific GitHub actions scripts into the [pulumi/pulumi](https://github.com/pulumi/pulumi/) repo, specifically a new subfolder of [/dist/docker](https://github.com/pulumi/pulumi/tree/master/dist/docker). 

That way we can build/push the new `pulumi/actions` Docker container image whenever we push a new update to the Pulumi CLI. And like discussed above, the `latest` tag will always contain the latest CLI. But we'll also automatically push version-specific tags too.
