### ISSUE TITLE
Deployment of multiple stack classes in program.cs 

### ISSUE THREAD

**Issue by dkezri** [pulumi/actions#1013]
i have two stack classes in my c# project 

classA: Stack
{
}
classB: Stack
{
}

this runs ok and creates  cloud resources
```
program.cs
{
   using Pulumi;
   await Deployment.RunAsync<stackA>();
}

```
when i try to deploy both stack classes in the program.cs  stops with the following error:
**pulumi:pulumi:Stack (dev):
    error: Duplicate resource URN '........'; try giving it a unique name**

```
program.cs
{
   using Pulumi;
   await Deployment.RunAsync<stackA>();
    await Deployment.RunAsync<stackA>();
}
```

i even tried this one  and same error:
```
program.cs
{
   using Pulumi;
  await Deployment.RunAsync(() =>
  {
      new AzureOidcStack();
      new MainStack();
  });
```
}

Is there any way to run multiple stack components/ classes  in program.cs file?

**Comment by simenandre** [comment]
This doesn't seem to be related to the Github Action. 

I suggest asking about this on [Slack](https://slack.pulumi.com/) or opening an issue on this on [pulumi/pulumi](https://github.com/pulumi/pulumi).
