### ISSUE TITLE
Documentation lists `output` as a supported command but action errors when using it.

### ISSUE THREAD

**Issue by mattotodd** [pulumi/actions#1078]
### What happened?

Trying to run pulumi output command but get an error saying its not a supported command:

```
Run pulumi/actions@v4
Error: Input was not correct for command. Valid alternatives are: up, update, refresh, destroy, preview
```

### Example

      - uses: pulumi/actions@v4
        id: pulumi_read_stack_info
        with:
          command: output
          work-dir: ./infra/
          stack-name: ${{ inputs.stack-name }}
          cloud-url: ${{ inputs.cloud-url }}   
          secrets-provider: ${{ inputs.secrets-provider }}

### Output of `pulumi about`

CLI          
Version      3.73.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME          VERSION
aws           5.43.0
mongodbatlas  3.12.1
python        unknown
random        4.15.0

Host     
OS       darwin
Version  12.0
Arch     arm64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mattotodd** [comment]
maybe a new version has not be tagged

**Comment by Frassle** [comment]
> maybe a new version has not be tagged

Yup, this only got merged recently and hasn't gone out in a tagged release.

**Comment by mattotodd** [comment]
thx @Frassle - how often do you release?    these feature is gonna be helpful for us

**Comment by tgummerer** [comment]
I just cut a release, so you should be able to get it now.  Note that you'll have to update to `pulumi/actions@v5`, as only that branch is getting updates now.  (I just realized that we need to update the README to say that, I'll do that now).

I'm gonna close this out, since the feature should be available in `pulumi/actions@v5` now.
