### ISSUE TITLE
Suppress progress dots

### ISSUE THREAD

**Issue by jjhuff** [pulumi/actions#1108]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
The CLI recent added support for  `--suppress-progress`. Adding an option to enable this would really cleanup our CI logs.

**Comment by justinvp** [comment]
Thanks for the suggestion, @jjhuff!

**Comment by mikocot** [comment]
This PR adds precondition to that change - adds parameter to stack automation which pulumi actions use. Feel free to pick it up from here, it's not a long way:
https://github.com/pulumi/pulumi/pull/15596

**Comment by mikocot** [comment]
pulumi automation changes have been released, hence I've created a PR for actions: 
https://github.com/pulumi/actions/pull/1116

Might need some additional testing :)
