### ISSUE TITLE
Allow specifying Python wrapper commands

### ISSUE THREAD

**Issue by fitz-vivodyne** [pulumi/actions#1117]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We're using pulumi with [poetry](https://python-poetry.org/), and for our local workflow run all commands via `poetry run pulumi <command>`.

This has made working with the official pulumi action a bit tricky (this also impacts pipenv users).

It would be nice if there was a way to specify that a wrapper should be used for python commans.

I initially looked at using a venv as recommended in https://github.com/pulumi/actions/issues/893, but there doesn't appear to be an env/cli flag we can set on pulumi that would allow us to use venv's without having to permanently modify `Pulumi.yaml`.

My current workaround is putting a wrapper around our python executable via the `PULUMI_PYTHON_CMD` env var and adding a `poetry-python` script in the repo:
```bash
#!/usr/bin/env bash
poetry run python "$@"
```

`PULUMI_PYTHON_CMD: ./poetry-python`

It would be nice if there was a native way to manage python wrappers natively in the action without requiring a wrapper script.

Related issues:
* https://github.com/pulumi/actions/issues/516
* https://github.com/pulumi/actions/issues/893

### Affected area/feature

GitHub Action?

**Comment by justinvp** [comment]
Thanks for the suggestion and sharing the workaround you're using in the meantime!

**Comment by benjy44** [comment]
I'm looking also for a solution to this, my current workaround for poetry is to add a step like this one:

```
      - name: Update Pulumi.yaml
        run: |
          venv_path=$(poetry env info --path)
          yq -i '.runtime |= . + {"options": {"virtualenv": "'${venv_path}'"}}' Pulumi.yaml
```

**Comment by julienp** [comment]
We haven't gotten around to adding documentation for this yet, but with https://github.com/pulumi/pulumi/pull/16315 we have native poetry support.

If you set the `toolchain` option to `poetry`, Pulumi will use Poetry to create a virtualenv during installation, and run your program within the context of that virtualenv. You can also add a `poetry.toml` file next to your `Pulumi.yaml` to configure Poetry https://python-poetry.org/docs/configuration/#local-configuration.

```yaml
name: pulumi-python-poetry
 description: A simple Python Pulumi program that uses Poetry.
 runtime:
   name: python
   options:
     toolchain: poetry
```

**Comment by fitz-vivodyne** [comment]
>Hi, sorry for necrobumping, but I'm having issues with uv toolchain. Running a pulumi/action with command: preview results with the follwing error:

Are you setting your `toolchain` to `uv`?
https://www.pulumi.com/blog/python-uv-toolchain/#using-uv-in-pulumi

**Comment by InCogNiTo124** [comment]
> > Hi, sorry for necrobumping, but I'm having issues with uv toolchain. Running a pulumi/action with command: preview results with the follwing error:
> 
> Are you setting your `toolchain` to `uv`? [pulumi.com/blog/python-uv-toolchain#using-uv-in-pulumi](https://www.pulumi.com/blog/python-uv-toolchain/#using-uv-in-pulumi)

yes I do, and still for some reason I need to `uv sync`.
