### ISSUE TITLE
Make `pulumi login` respect configuration in `Pulumi.yaml`

### ISSUE THREAD

**Issue by tgummerer** [pulumi/actions#1120]
While working on https://github.com/pulumi/actions/issues/1081, we noticed that `pulumi login` wasn't respecting the configuration in `Pulumi.yaml`, and thus errored out when no `cloud-url` was given in the action.  We should improve `pulumi login`, so it takes the setting in `Pulumi.yaml` into account if that file is available to reduce confusion for users.

/xref https://github.com/pulumi/home/issues/3298

**Comment by Frassle** [comment]
OK had a look into this and `pulumi login` _does_ respect the backend set in the Pulumi.yaml. It looks like the issue is actions isn't running the initial login command in the same directory as all the other commands.
