### ISSUE TITLE
Using latest for pulumi-version option does not properly match the current and latest versions.

### ISSUE THREAD

**Issue by j-fulbright** [pulumi/actions#1221]
### What happened?

![image](https://github.com/pulumi/actions/assets/10793868/ec0d531d-432f-4def-b0d6-6afb5b18bddd)

This does not affect functionality, but one less thing to have to download or deal with in the process

### Example

See above

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tgummerer** [comment]
Thanks for opening the issue.  Currently when `pulumi-version: latest` is specified we'll always try to download the latest version of the CLI, regardless of what's installed.  

https://github.com/pulumi/actions/pull/1225 moves that around, so we get the latest version first, and if that matches the currently installed version we won't download it.

Note that in the meantime you can work around this by removing the `pulumi-version` directive.  That means you'll be using the version installed on the runner by default, and a newer version only gets installed if pulumi is not installed on the runner, or if we marked the version that is installed as a known bad version.
