### ISSUE TITLE
Colors code on comment should not be printed

### ISSUE THREAD

**Issue by notdodo** [pulumi/actions#1228]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The action allows to enable `color` with `auto` (default), `raw`, `never` and `always`.
The action allows to show a `comment-on-pr` for the preview.

It's not possible to enable colors only for the GHA output:
1. enable `color: always`
2. the preview/output in the "Actions" github page is shown with colors
3. the output in the comment of the PR contains color and escape codes

Should be fair to allow colors only for the "Actions" pulumi output and not in the comment of the PR.

### Affected area/feature

Pulumi output/colors

**Comment by justinvp** [comment]
Thanks for the suggestion!

**Comment by notdodo** [comment]
https://github.com/pulumi/actions/pull/859

**Comment by notdodo** [comment]
https://github.com/pulumi/actions/pull/1231

**Comment by tgummerer** [comment]
https://github.com/pulumi/actions/pull/1231 has been merged and released, so I think this can be closed.  Please let us know if this is still not working as desired.

**Comment by neilprosser** [comment]
Related to this. I'm seeing color-related characters in the GitHub step summary when `color: always` and `comment-on-summary: true` are both set.

**Comment by tgummerer** [comment]
@neilprosser can you please open a new issue for that if you're still seeing that in the latest release?  This will allow us to keep tracking that, a comment in a closed issue is likely to be lost.

**Comment by neilprosser** [comment]
No problem. Done and created #1248.
