### ISSUE TITLE
Support the --config-file feature

### ISSUE THREAD

**Issue by yfried** [pulumi/actions#165]
Please allow to provide an external config file.
This can be done via CLI, but not supported here.

**Comment by asadoughi** [comment]
+1 It's not clear to me how `upsert: true` should work if we are unable to set custom stack configuration.

**Comment by cobraz** [comment]
> +1 It's not clear to me how `upsert: true` should work if we are unable to set custom stack configuration.

@asadoughi You can set stack with the `stack-name` input. So, let's say you are setting up a temporary stack, you can use `upsert` to create a stack named what you defined in `stack-name`. Using `upsert` would create a `Pulumi.<stack-name.yml` on your Github Actions runner.

**Comment by abiro** [comment]
@cobraz but how do you pass it custom configuration values?

**Comment by cobraz** [comment]
> @cobraz but how do you pass it custom configuration values?

There are no fields for all custom values, but which values do you wanna set?

**Comment by abiro** [comment]
@cobraz I mean stack input parameters, eg. if I'm using `@pulumi/aws`, I have to set `aws:region`.

**Comment by tomdavidson** [comment]
Just doing in the code base is certainly a legit path but why should that be the ONLY path? Particularly if dealing with legacy code that you would rather configure than change the code.

Looking at #117 @cobraz  set it up the options functionality quite nice. Wouldn't it be easy & safe to add `config-file` and `set-all`?  Is this something Pulumi is interested in a contrib or does pulumi want to for the in code base path?

**Comment by hermanbanken** [comment]
Maybe also add `args`, so users can add any cli arg, like `-c` for config override support. For example, we'd like to inject the Docker Image tag using `-c docker:image=nginx:4242`.
