### ISSUE TITLE
Explicit stack

### ISSUE THREAD

**Issue by prepor** [pulumi/actions#17]
Hey. I want to manually provide a stack to Pulumi Github Action

From comments (https://github.com/pulumi/pulumi/blob/master/dist/actions/entrypoint.sh#L45):

> the caller of this script will need to pass `-s <stack-name>` to specify the stack explicitly

But it actually fails even if I provide `-s` argument, doesn't it? Maybe we can add an ability to explicitly provide stack name via `PULUMI_STACK_NAME` environment variable?

**Comment by chrsmith** [comment]
Yup, honoring a `PULUMI_STACK_NAME` environment variable is a good idea.

**Comment by prepor** [comment]
For reference: I solved this (and some other) issue by alternative action without Docker https://github.com/prepor/github-pulumi

**Comment by stack72** [comment]
Closed as being tracked in #40

**Comment by stack72** [comment]
I am closing this out as we have just released v2 of our Action which is based on TypeScript and addresses this issue
