### ISSUE TITLE
Incorrect install-pulumi-cli action version in the README

### ISSUE THREAD

**Issue by tlinhart** [pulumi/actions#182]
The [getting started](https://github.com/pulumi/actions#getting-started) example refers to using `pulumi/action-install-pulumi-cli@v1`, however this leads to an error:

```
Error: Unable to resolve action `pulumi/action-install-pulumi-cli@v1`, unable to find version `v1`
``` 

It should refer to using `pulumi/action-install-pulumi-cli@v1.0.1`.

**Comment by stack72** [comment]
Sorry about that @tlinhart - we will get that updated right now!

**Comment by stack72** [comment]
Hi @tlinhart 

All taken care of!!

Please let me know if there are any issues

Paul
