### ISSUE TITLE
Major version mismatch with actions@v2 due to CLI 3.x

### ISSUE THREAD

**Issue by njbmartin** [pulumi/actions#198]
This screenshot should probably give enough information:

![image](https://user-images.githubusercontent.com/5699471/115875842-8f5b0780-a43d-11eb-8d49-b52d9be11916.png)

Looks like `pulumi/action-install-pulumi-cli@v1.0.1` has no version pinning, so it installs CLI v3, when the v2 action is being used.

**Comment by njbmartin** [comment]
Following the getting started example would fail:
https://github.com/pulumi/actions#getting-started

**Comment by stack72** [comment]
Hi @njbmartin 

You can pass

With:
  Pulumi-version: 2.25.2

And that will pin the version for you. We give an example in the README

Paul

**Comment by njbmartin** [comment]
> Hi @njbmartin
> 
> You can pass
> 
> With:
> Pulumi-version: 2.25.2
> 
> And that will pin the version for you. We give an example in the README
> 
> Paul

Thanks Paul, but it might be worth looking at how you provide examples. You say you give an example in the readme, but that's in the https://github.com/pulumi/action-install-pulumi-cli readme.

If you look at the example given here: https://github.com/pulumi/actions#getting-started

it would break.

**Comment by ryanbeales321** [comment]
Been looking at this this morning.

To continue using pulumi CLI v2:
Use `pulumi-version: 2.25.2` with pulumi/action-install-pulumi-cli@v1.0.1

To use pulumi CLI v3:
Update your github actions workflow to pulumi/actions@v3

**Comment by cobraz** [comment]
@ryanbeales321 Thanks for that! We'll update the README very soon :)

**Comment by stack72** [comment]
Closed via #211 

We will handle the usage of the CLI internally and not require to need to think about the CLI
