### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [pulumi/actions#199]
It has been noticed that while using mshick/add-pr-comment@v1 your repo-token-user-login pulumi-bot is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by cobraz** [comment]
Hello, thanks for filing this issue!

How exactly are the token being presented in plaintext? Can you give us an example workflow?

**Comment by cobraz** [comment]
From what I'm seeing we're already using a secret. I'll close this comment for now, but if you have more information to share, please go ahead and comment and I'll have a look :)
