### ISSUE TITLE
Improve Pull Request comments

### ISSUE THREAD

**Issue by cobraz** [pulumi/actions#200]
After #148 is merged, there are two things I think we should add.

- [ ] Add stack name to pull request comment
- [ ] Search for comments that starts with `#### :tropical_drink: <command> on <stack name>`

This way we update only pull request comments that are for the same stack and command.

We should consider making updating pull request comments the default way.

**Comment by grahamplata** [comment]
I can update that. I ran into that need recently 👍

**Comment by cobraz** [comment]
Thank you! 🙏
