### ISSUE TITLE
Allow usage of local pulumi policy pack

### ISSUE THREAD

**Issue by wvanderdeijl** [pulumi/actions#212]
We are trying to move from running plain pulumi cli in github actions to the actual `pulumi/action` since that would support editing/replacing the same PR comment instead of flooding the PR comments by the pulumi github app.

But the one feature I seem to be missing is the equivalent of the `--policy-pack ../pulumi-policy` CLI argument. We run a (large) monorepo and have the policy files in the same repo and refer to the locally when doing a pulumi up or preview.

**Comment by FreebeJan** [comment]
First of all: Thanks to all involved contributors for providing this action. 

We are looking forward to this feature! I see in the milestone that it should be released in a couple of days. Is that certain?

**Comment by FreebeJan** [comment]
Hi again, can I contribute to bring this feature? Where would be a good place to start looking at?

**Comment by stack72** [comment]
Hi @FreebeJan 

My apologies for not getting back to you on this - this needs to be added to the underlying automation api first and then we can add to the action

It's in progress

P.

**Comment by FreebeJan** [comment]
Any news on this issue?

**Comment by FreebeJan** [comment]
ping

**Comment by FreebeJan** [comment]
ping

**Comment by FreebeJan** [comment]
ping!

**Comment by ShedPlant** [comment]
I would also be interested in this feature.

**Comment by cobraz** [comment]
Hello! Thanks for the update, that surely helps us prioritize this issue.

Going forward, I would love if people to up-voted if they are interested in this feature (👍).
It makes more sense for us when we prioritize.

Thank you!

**Comment by alexrocco** [comment]
Any update?

**Comment by FreebeJan** [comment]
Any changes to the priority of this? I want to express that I am not too happy with the communication concerning this issue

1.  I was asking where I could implement this myself as I really need this feature and was told here that the pulumi team is working on it: https://github.com/pulumi/actions/issues/212#issuecomment-861667892
2. Almost a year later you tell us to give thumbs ups to this issue so you can priorize this (https://github.com/pulumi/actions/issues/212#issuecomment-995242821)

To go full-circle on this one: where can we start looking to implement this ourselves?

**Comment by abargstaedt** [comment]
IMHO this is a must have. Unless we can't run policy tests in our pipeline it's not even worth implementing them in the first place.
