### ISSUE TITLE
Question: Is there a way to fix the Pulumi version?

### ISSUE THREAD

**Issue by renannprado** [pulumi/actions#216]
So we have been getting Pulumi updates in our pipelines without any notice. 

We would like to be able to use the action, but still choose when to upgrade Pulumi, is there a way to set the Pulumi version that will be used?

**Comment by stack72** [comment]
Hi @renannprado 

Areyou talking about the Pulumi CLI? If so, are you using an action as follows:

```
      - uses: pulumi/action-install-pulumi-cli@v1
```

if so, then you can do as follows:

```
      - uses: pulumi/action-install-pulumi-cli@v1
      	with:
			pulumi-version: 3.2.0
```

Paul

**Comment by renannprado** [comment]
@stack72 I missed this detail. My bad. 

True, I haven't set it in my install action usage. 

Thanks!

**Comment by renannprado** [comment]
@stack72 since the `pulumi/action-install-pulumi-cli` is no longer necessary. How can I set the `pulumi-version` using the latest `pulumi/actions@v3`? in this case, should I still use `pulumi/action-install-pulumi-cli`?

**Comment by stack72** [comment]
Hi @renannprado 

So the action will track the current latest *minor* version of the CLI - that's just an implementation detail of this under the hood - we have to do this as the Automation API is currently closely related to the CLI

You don't need to set any specific values anymore - we handle this internally

P.
