### ISSUE TITLE
Should error on missing stack configuration

### ISSUE THREAD

**Issue by chrisportela** [pulumi/actions#22]
We were getting passing builds in our deploy workflow, but the task was actually not configured for this branch. We're using the config as explained in the README.

Is there something we missed or need to add in our configuration to make sure the task fails if it can't find a proper configuration?

**Comment by pgavlin** [comment]
cc @chrsmith @joeduffy

**Comment by stack72** [comment]
Closed as being tracked in #40

**Comment by stack72** [comment]
I am closing this out as we have just released v2 of our Action which is based on TypeScript and addresses this issue
