### ISSUE TITLE
Action does not fail

### ISSUE THREAD

**Issue by GaboFDC** [pulumi/actions#27]
The action should fail when there are errors.
In this case, no cloud backend config was provided, pulumi outputed the error, but the action didn't fail

![image](https://user-images.githubusercontent.com/1425500/87203797-fd787880-c2c8-11ea-87c0-84cfa65e1786.png)

Not sure, but some other errors may also be passing.

**Comment by stack72** [comment]
Closed as being tracked in #40

**Comment by infin8x** [comment]
Closing this in favor of #40, please comment if you disagree

**Comment by infin8x** [comment]
Reopening this after chatting with @leezen, since this is just one component of #40

**Comment by stack72** [comment]
I am closing this out as we have just released v2 of our Action which is based on TypeScript and addresses this issue
