### ISSUE TITLE
GCP Artifact Registry authenitication

### ISSUE THREAD

**Issue by OliverHGray** [pulumi/actions#28]
I am using the action to run a Pulumi script that builds a Docker image, pushes it to Artifact Registry and then upgrades a service on Cloud Run. This works fine locally, but when I run it in the action using a service account with the Owner role, I get a permissions problem for the docker step. These are the errors: 

```
docker push europe-west1-docker.pkg.dev/<project>/docker/specifications:v1.0.29-3689a637972026c4d33c3b2021c44caf7d5f8e99f679a6b0da744d89438d2874' failed with exit code 1

Permission "artifactregistry.repositories.downloadArtifacts" denied on resource "projects/<project>/locations/europe-west1/repositories/docker" (or it may not exist)
```

Removing the Docker step and just doing the cloud run upgrade works fine.

**Comment by leezen** [comment]
When you run this locally, are you also using the service account? Have you verified it's running w/ the same service account when using the action?

**Comment by OliverHGray** [comment]
I can reproduce it locally if I remove the Docker credential helper for Artifact Registry, is there currently a way to add a credential helper in the action?

**Comment by leezen** [comment]
Ah -- interesting. So https://github.com/pulumi/pulumi/blob/master/dist/actions/entrypoint.sh#L91 actually is somehow making this not work for you? Or is that not being executed correctly for you?

**Comment by OliverHGray** [comment]
Yeah, I believe just `gcloud auth configure-docker` will only add helpers for Container Registry:

```
"gcr.io": "gcloud", 
"marketplace.gcr.io": "gcloud", 
"eu.gcr.io": "gcloud",
"us.gcr.io": "gcloud", 
"staging-k8s.gcr.io": "gcloud", 
"asia.gcr.io": "gcloud"
```

Whereas Artifact Registry requires you give it the name of the region the repository is in: `gcloud auth configure-docker europe-west1-docker.pkg.dev`, and it will also add a helper for Artifact Registry in that region:

```
"gcr.io": "gcloud", 
"marketplace.gcr.io": "gcloud", 
"eu.gcr.io": "gcloud",
"europe-west1-docker.pkg.dev": "gcloud", 
"us.gcr.io": "gcloud", 
"staging-k8s.gcr.io": "gcloud", 
"asia.gcr.io": "gcloud"
```

**Comment by leezen** [comment]
Got it -- thanks. Sounds like we should extend the entrypoint to allow for configuring additional registries as an option. Care to submit a PR?

**Comment by OliverHGray** [comment]
Sure, is this what you imagined? https://github.com/pulumi/pulumi/pull/5075

**Comment by OliverHGray** [comment]
Just wondering - this is still in PR, has it fallen off the radar? Figured it was quite an innocuous change

**Comment by leezen** [comment]
@OliverHGray Sorry about that -- it did slip my mind. I updated the PR with a comment.

**Comment by OliverHGray** [comment]
No problem, I've updated it as per your comment
