### ISSUE TITLE
Error building AzureRM Client

### ISSUE THREAD

**Issue by dfinke** [pulumi/actions#3]
# Error
```
warning: A new version of Pulumi is available. To upgrade from version '0.16.6' to '0.16.8', visit https://pulumi.io/install for manual instructions and release notes.
Previewing update (production):

 +  pulumi:pulumi:Stack tryPulumiAction-production create 
    azure:core:ResourceGroup resourceGroup  error: Error building AzureRM Client: Azure CLI Authorization Profile was not found. Please ensure the Azure CLI is installed and then log-in with `az login`.
    azure:core:ResourceGroup resourceGroup  1 error
 
Diagnostics:
  azure:core:ResourceGroup (resourceGroup):
    error: Error building AzureRM Client: Azure CLI Authorization Profile was not found. Please ensure the Azure CLI is installed and then log-in with `az login`.
 
error: an error occurred while advancing the preview
```

# main.workflow

```
workflow "Update" {
    on = "push"
    resolves = [ "Pulumi Deploy (Current Stack)" ]
}

action "Pulumi Deploy (Current Stack)" {
    uses = "docker://pulumi/actions"
    args = [ "up" ]
    env = {
        "PULUMI_ROOT" = "infra",
        "PULUMI_CI" = "up"
    }
    secrets = [
        "PULUMI_ACCESS_TOKEN"
    ]
}
```

**Comment by joeduffy** [comment]
I *think* you will need to use a service principal for this. See https://pulumi.io/quickstart/azure/setup.html#service-principal-authentication for details on how to configure this -- you can either use Pulumi config to do this or the GitHub Secrets in your repo.

I'll give this a try in a little bit and report back, but if you get a chance, please let us know if it works.

**Comment by dfinke** [comment]
I did set that up. Took these settings from the service principal I created and successfully used in an Azure DevOps pipeline with pulumi.

![image](https://user-images.githubusercontent.com/67258/50385778-477b1880-06a9-11e9-81bf-da77bea4ef38.png)

**Comment by joeduffy** [comment]
I was able to repro this when running in GitHub Actions. Strangely, it seems to work fine when running the same `pulumi/actions` Docker image locally with the various `ARM_*` service principal variables set.

Still debugging...

**Comment by joeduffy** [comment]
@dfinke I think I've figured out what's going on here. GitHub only seems to map environment variables from secrets into actions that have declared those secrets as inputs.

So, from your example workflow above, simply add the `ARM_*` lines to the `secrets`:

```
workflow "Update" {
    on = "push"
    resolves = [ "Pulumi Deploy (Current Stack)" ]
}

action "Pulumi Deploy (Current Stack)" {
    uses = "docker://pulumi/actions"
    args = [ "up" ]
    env = {
        "PULUMI_ROOT" = "infra"
        "PULUMI_CI" = "up"
    }
    secrets = [
        "PULUMI_ACCESS_TOKEN",
        "ARM_SUBSCRIPTION_ID",
        "ARM_CLIENT_ID",
        "ARM_CLIENT_SECRET",
        "ARM_TENANT_ID"
    ]
}
```

I believe this behavior must have changed at some point recently -- the joys of a preview feature :smile:

I will update the `README` in this repo to make this clearer.

**Comment by joeduffy** [comment]
Updated the README (https://github.com/pulumi/actions/commit/b5a2c4a5bca93db30bce85a911bf11ce903f4bf2) and also the pulumi.io website docs (https://github.com/pulumi/docs/commit/8db0946584f79d6a580e64001e13c018c08d3741).

Going to close this out now -- please let me know if it does/does not work!
