### ISSUE TITLE
Github Bot should edit previous comment instead of posting new one.

### ISSUE THREAD

**Issue by Hawxy** [pulumi/actions#31]
It would cut down on spam in busy PRs if the Github bot posted a single comment and edited it, instead of posting a new comment every time. This would be consistent with other github bots such as Vercel or Cypress. This also comes with the advantage that the latest preview information is always kept towards the top of the comments, regardless of the number of commits/comments/etc.

I imagine this would be more practical to do once #29 is in.

**Comment by cobraz** [comment]
This is released in pulumi/action@3.1.0!
