### ISSUE TITLE
Provide a lighter docker image

### ISSUE THREAD

**Issue by fpoliquin** [pulumi/actions#34]
Currently, the docker image containing the pulumi actions is around 900 MB and takes over 1 minute to pull for every invocation. Could it be possible to use a different, lighter, base image to run pulumi. Maybe based on alpine ?

**Comment by stack72** [comment]
Closed as being tracked in #40

**Comment by stack72** [comment]
I am closing this out as we have just released v2 of our Action which is based on TypeScript and addresses this issue
