### ISSUE TITLE
Add option to collapse the PR comment

### ISSUE THREAD

**Issue by renannprado** [pulumi/actions#344]
## PR comment

In some situations you might get a PR comment from Pulumi that's way too big, which causes you to have to scroll a lot before getting to next comment in the PR.

The feature request is:

* either add a config option to the pulumi action which causes the action to post a collapsed comment (preferable IMHO)
* always post a collapsed comment

### Sample comment

<details>
  <summary>Click here to see pulumi up/preview output</summary>
  
### Some huge pulumi output
</details>

**Comment by cobraz** [comment]
Thank you so much for opening up this issue!

There are two ways you can achieve this today. As outlined in [my comment in #158](https://github.com/pulumi/actions/issues/158#issuecomment-813009731), you're able to turn off pull request comments and use other more feature-rich Github Actions. Other than that, personally, I use [refined-github](https://github.com/sindresorhus/refined-github) which collapses it automatically.

I don't know if it fits for us to add this, but we'll get back to you on it!

Thanks again!

**Comment by renannprado** [comment]
@cobraz thanks for the reply and thanks for pointing me out to the extension. 

I believe though asking everyone to use the extension is not so nice, neither stop using the comment from the action to use another one instead. I mean, it's not difficult to implement as you say, indeed it would work, and it's part of the "philosophy" of github actions in way. But you guys already put effort in, for example, editing the comment rather than create new ones, which is very much appreciated btw. So, in my humble opinion, I see the collapsable comment feature as a cherry on top of the comment feature you already provide and is working really well :smile: .

**Comment by tomdavidson** [comment]
Adding to @renannprado's comment, I would say the value of the action is better DX then just installing the CLI and invoking it directly. If DX not the indented goal Pulumi has with this action, perhaps the intentions can be shared in the README.md so the community can have aligned expectations.

**Comment by tomdavidson** [comment]
Just read #310 where I think single purpose actions make sense but without that decomposition, the current action has all the DX.

**Comment by cobraz** [comment]
This is released in 3.16.0 :)
