### ISSUE TITLE
(v2) Javascript-based Github Actions

### ISSUE THREAD

**Issue by cobraz** [pulumi/actions#37]
Hello 👋

I thought it would be useful to have an issue to track the efforts of making a new Pulumi Github Actions, based on Javascript. As @chrsmith wrote about in #29, there are still things to consider and decide. Below you'll find my list of features I think we should add as well.

- [ ] Add tests
- [ ] Add PULUMI_CI_* environment variables
- [ ] Add `.pulumi/ci.json` configuration
- [ ] Add stack name input variable
- [ ] Add updated documentation
- [ ] Add PR comment functionality

cc: @chrsmith @praneetloke @jaxxstorm

re #23

**Comment by chrsmith** [comment]
CC @stack72 , who has been driving part of our GitHub Actions story recently.

**Comment by stack72** [comment]
Closed as being tracked in #40

**Comment by stack72** [comment]
I am closing this out as we have just released v2 of our Action which is based on TypeScript and addresses this issue
