### ISSUE TITLE
Have an ability to change pulumi cli version

### ISSUE THREAD

**Issue by XBeg9** [pulumi/actions#437]
https://github.com/pulumi/actions/blob/0aa3bec9b0664936ca07f3041a848fedd3919829/src/main.ts#L14

Is there a specific reason why we can't control pulumi cli version?

**Comment by stack72** [comment]
Hi @XBeg9 

So the use of the CLI internally to the actions is purely an implementation detail based on the fact that the action uses the automation api. The automation api needs the cli and it's kinda coupled with it. If you try and use the automation api with a non-compatible version of the cli then an error can occur

So we are coupling the version of the automation api with the version of the cli

If you feel this is bad practice then we can change it but it would still need to be the default version that is coupled.

Paul

**Comment by Place1** [comment]
I've experienced bugs in minor/patch releases of the Pulumi CLI. It's not fun but it's something that happens to all software.

It'd be great if the action allowed users to specify which CLI version they need to work around bugs :)

**Comment by cobraz** [comment]
We could check if the user-defined version is within the range the action requires. This could be something the end user sees as a warning?

What do you guys think, @Place1 and @stack72?

**Comment by RobbieMcKinstry** [comment]
I'm suggesting we add a warning to check if the requested `version` is beneath `v3` in [this PR](https://github.com/pulumi/actions/pull/661).
