### ISSUE TITLE
(v2) Configuration handling

### ISSUE THREAD

**Issue by cobraz** [pulumi/actions#45]
In the current `action.yml` file, we have configured the following:

https://github.com/pulumi/actions/blob/25b22d49a02b9fec359213f05a4751c6a2d71393/action.yaml#L7-L13

(Don't mind the typo 😅)

Do we need more variables?

I am thinking about using [runtypes](https://github.com/pelotom/runtypes) to determine if our configuration is valid. Any thoughts?

**Comment by stack72** [comment]
There will definitely be more - right now, there are a lot of env vars set to do this work but these will be replaced by inputs e.g. cwd for where Pulumi files live

Happy for you to look at `runtypes` not used that before but if you think it's useful then we can
