### ISSUE TITLE
Customising the `pulumi` command

### ISSUE THREAD

**Issue by aetheryx** [pulumi/actions#554]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I'm working with a Yarn PnP TypeScript monorepo, where one of the apps in the monorepo is the Pulumi infrastructure. Because [Pulumi doesn't support PnP out of the box](https://github.com/pulumi/pulumi/issues/3586), I have to run the `pulumi` CLI with [the `PnPify` compatibility layer](https://yarnpkg.com/advanced/pnpify). So instead of `pulumi preview`, I run `yarn workspace infra pnpify pulumi up` (or `yarn pnpify pulumi up` from the `infra` workspace).  

The PnPify solution works great locally, but this action doesn't seem to support changing the `pulumi` command. 

### Affected area/feature

I see at least a few hardcoded references to `pulumi` here: https://github.com/pulumi/actions/blob/master/src/libs/pulumi-cli.ts#L9-#L16  
But after briefly tinkering with it, it seems to me the actual commands just call Stack methods from the `@pulumi/pulumi/automation` library - unsure

**Comment by RobbieMcKinstry** [comment]
IIRC the automation API uses the underlying Pulumi CLI binary. So if the Action uses the automation API library, then it's probably still using the version of Pulumi fetched by the action. However, I'm tracing the library a little differently:

1. [This](https://github.com/pulumi/actions/blob/master/src/libs/exec.ts#L10-L14) is the function responsible for shelling out whatever command is passed in.

2. [This line](https://github.com/pulumi/actions/blob/master/src/libs/pulumi-cli.ts#L14) selects `pulumi` as the name of the binary, and forwards a list of args to the `exec` function from Step (1).

3. This line calls the `run` function above to log in to Pulumi Service state backend.

4. [These lines](https://github.com/pulumi/actions/blob/master/src/main.ts#L63-L77) use Automation API to run the operation.

To get your command to work with this action, I think you'd need to alias the `pulumi` command to a wrapper script that uses your command (replacing `yarn workspace infra pnpify pulumi up` with `yarn workspace infra pnpify /path/to/pulumi/binary up`).

That sounds like it would be challenging and invasive. I'm wondering if it would be easier to address your initial concern about PnP than to modify this Action to support that use case.

I'm afraid I'm not familiar enough with PnP to determine what would block https://github.com/pulumi/pulumi/issues/3586 from making progress.

**Comment by RobbieMcKinstry** [comment]
Hey there @aetheryx. If you want to wrap the `pulumi` CLI in a subprocess, the recommended resolution, for now, is to use [`pulumi/setup-pulumi`](https://github.com/marketplace/actions/setup-pulumi) to install the CLI into your `PATH`. After that, you should be able to run `yarn workspace infra pnpify pulumi up` or any other `pulumi` command using the installed binary.

In the next couple of releases, it's likely we'll add an `install` command to this action so you won't need to use `pulumi/setup-pulumi` anymore. For more info or to follow along, see https://github.com/pulumi/actions/issues/686

It would be great if, in the future, the Pulumi CLI could support PnP out of the box as you noted, but I don't think we are likely to support adding a custom command. I would encourage you to stick with your existing solution, which I would code something like this:

```yml
- name: Install Pulumi CLI
   uses: pulumi-contrib/setup-pulumi@v1
- name: Pnpify Pulumi Preview
   run: yarn workspace infra pnpify pulumi preview
- name: Pnpify Pulumi Up
   run: yarn workspace infra pnpify pulumi up
```

I'm going to close this issue for now, but please feel free to reach out if you have more to discuss!
