### ISSUE TITLE
Question: Release cadence

### ISSUE THREAD

**Issue by renannprado** [pulumi/actions#669]
I would like to ask the maintainers how often do you release/plan to release?

My main pain point today is #633, which is has been fixed already. But the releases seem not to happen frequently enough.

So I would like to kindly ask whether it's possible to increase the release cadence or maybe even have a schedule (e.g. once a week, every two weeks). Something that we, the users, can rely on when we know that there are important updates coming.

Thanks!

**Comment by RobbieMcKinstry** [comment]
Hi @renannprado! I'd like to get an answer to you soon! I think you're right, the releases are very infrequent and irregular. From what I can tell ownership of this repo has recently changed hands, so we're planning to solidify a release cadence and come up with an answer for you soon.
I'm away from my computer during the next couple of days for the holiday, but when I get back I'll see if we can get this settled.

**Comment by RobbieMcKinstry** [comment]
Hey there, following up on this!
The answer is "monthly!" We added that information to the [README](https://github.com/pulumi/actions#release-cadence).
Thanks for prompting us to increase our transparency! This is a good section to have in the README, as it helps inform our users of what they can expect when working with (this) Pulumi tool(s).
