### ISSUE TITLE
Question: getVersionObject is it possible to turn it off?

### ISSUE THREAD

**Issue by bitdevel** [pulumi/actions#674]
### What happened?

In our environment we do not want to have outgoing traffic to the internet but in` https://raw.githubusercontent.com/pulumi/actions/master/dist/index.js` we see `function downloadCli` that calls `getVersionObject`.  Is it possible to somehow turn it off?

### Steps to reproduce

n/a

### Expected Behavior

no outbound traffic to the internet

### Actual Behavior

outbound traffic to the internet

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by cobraz** [comment]
Thanks, @bitdevel for posting this!

You're right, we should probably add some way to deactivate the functions that download stuff. How are you solving downloading the pulumi cli, just have it downloaded on the runner?

**Comment by mikhailshilkov** [comment]
Yes, @bitdevel, could you please describe your target scenario for version/download resolution? That function is used to fine a version of pulumi and its download location, how would you want to override it? Some sort of environment variables?

**Comment by RobbieMcKinstry** [comment]
@bitdevel just wanted to follow up on your question. 

Would you mind taking a minute to describe how you've installed the Pulumi CLI if not using the outbound network? And how you'd prefer version resolution to be performed? I can image an `offline=true` setting, but I'm curious about the edge cases others have asked about.

> could you please describe your target scenario for version/download resolution? That function is used to find a version of pulumi and its download location, how would you want to override it? Some sort of environment variables?

Thanks for your time and input! It's much appreciated as we iterate. :D

**Comment by RobbieMcKinstry** [comment]
Another consideration: an `offline` mode is incompatible with... most backends. You could use the file state backend but not a cloud storage backend or the Pulumi service. Not sure how we'd handle that.

**Comment by bitdevel** [comment]
Basically in our  networking setup we do not have accesss to the internet. Pip repository is mirrored in our network, we also have rules allowing to access AWS s3. This specific function tries to go directly to the internet.

**Comment by cobraz** [comment]
> Basically in our networking setup we do not have accesss to the internet. Pip repository is mirrored in our network, we also have rules allowing to access AWS s3. This specific function tries to go directly to the internet.

In that case, one solution could be to open up this:
https://raw.githubusercontent.com/pulumi/docs/master/data/versions.json

**Comment by RobbieMcKinstry** [comment]
@cobraz On Tuesday you mentioned that GHA runners come with Pulumi pre-installed, and that we could assume if the user doesn't specify a version, we could skip the installation step altogether. That might solve the original issue.

I'm not sure "offline" mode would make sense since we still need a way to store state (beyond the file backend), and we can't tell which IPs are allowlisted and denylisted.

**Comment by cobraz** [comment]
> @cobraz On Tuesday you mentioned that GHA runners come with Pulumi pre-installed, and that we could assume if the user doesn't specify a version, we could skip the installation step altogether. That might solve the original issue.

This is not the case with self-hosted runners, which is probably the case here.


> I'm not sure "offline" mode would make sense since we still need a way to store state (beyond the file backend), and we can't tell which IPs are allowlisted and denylisted.

Right, I forgot about that. I agree, I don't think “offline” makes sense. It makes more sense to whitelist, potentially add a input argument to disable downloading Pulumi.

**Comment by RobbieMcKinstry** [comment]
Closing this issue as it's not actionable at this time, and a workaround exists. Also, https://github.com/pulumi/actions/issues/789 if implemented would eliminate the need to download the CLI
