### ISSUE TITLE
Support an Installation-Only Workflow

### ISSUE THREAD

**Issue by RobbieMcKinstry** [pulumi/actions#686]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Requesting feedback from the wider team on this one.

A couple of users have opened issues expressing confusion on how to use this tool with workflow patterns that involve executing the `pulumi` CLI in a subprocess.

* [Subprocessing Pulumi from inside Yarn for performance](https://github.com/pulumi/actions/issues/554)
* [Running Pulumi with Pipenv](https://github.com/pulumi/actions/issues/516)

This functionality can be implemented using the `setup-pulumi` action. However, appears that the [`setup-pulumi`](https://github.com/marketplace/actions/setup-pulumi-cli) action isn't as discoverable as this one. Our documentation doesn't make a strong distinction between the two, or when to use one _vs._ the other. (I only recently became aware of the other action!) Our [CI/CD documentation page ](https://www.pulumi.com/docs/guides/continuous-delivery/github-actions/)doesn't describe the `setup` action at all. It could benefit from an `Advanced Features` section describing the `setup` action and when to use it. The setup action has 34 Marketplace stars compared to 149 stars on this action.

While I'm not aware of an existing idiom for GH Action, I know that CircleCI orbs have an idiom where they expose a command to install the binary as an escape hatch so users who need access to the tool at a lower level of abstraction can install it. 
Examples in CircleCi:

* [Helm](https://circleci.com/developer/orbs/orb/circleci/helm#commands-install-helm-client)
* [Kubectl](https://circleci.com/developer/orbs/orb/circleci/kubernetes#usage-install-kubectl) 
* [EKS](https://circleci.com/developer/orbs/orb/circleci/aws-eks#commands-setup)

Nevertheless, the `setup-pulumi` action is stable and works well! If it ain't broke, don't fix it. Similarly, I know some have expressed a desire for "Unix-style tools" as much as possible. On one hand, I don't see a need to shake things up and deprecate a working Action requiring little maintenance. On the other, there's definitely little use for the action 

I would consider a resolution to this issue part of a First-48 Hours experience for many users coming to Pulumi with existing workflows.

## Possible Improvements

Here are two possible resolutions:

1. Improve our documentation to increase awareness of the `pulumi-setup` action and point users to the that action when they request something lower level.

2. Expose an `install` command to this action, and deprecate the `pulumi-setup` action (it hasn't received a commit since November because it's quite stable). This repo already install `pulumi` CLI, so the change would be very small and easy to support. We would return early from main after calling [`downloadCLI`](https://github.com/pulumi/actions/blob/master/src/libs/pulumi-cli.ts#L33) [here](https://github.com/pulumi/actions/blob/master/src/main.ts#L22).

While I'd be content with either of these resolutions, I think we should take "a little bit of column A and a little bit of column B". 

* Improve the documentation on the Docs site
* Add the install command to this action, since it's a couple of lines to fix and centralizes the workflows for most users, increasing discoverability.
* Leave the `setup-pulumi` but determine some long-term fate for the tool. As described in https://github.com/pulumi/actions/issues/310 it would be really useful to have a common NPM package to share installation code with the AZ DevOps Pipeline action and the CircleCI Orb (**nb** I haven't looked into the CCI repo yet).

### Affected area/feature

Docs, and potentially the list of commands on this action.

**Comment by dixler** [comment]
I was about to say that CI/CD seems beyond the first 48 hours, but I think that might be a shortcoming and an opportunity for enhancement. I hadn’t thought of it. Maybe we could tie it in with a get started guide or learn pathway.

**Comment by RobbieMcKinstry** [comment]
I definitely came to [the user guide](https://www.pulumi.com/docs/guides/continuous-delivery/github-actions/) in my first 48 hours w Pulumi, but perhaps I'm the expectation and not the norm. I believe some of our competitors consider it part of onboarding.

**Comment by cobraz** [comment]
I really like your thoughts here, I think it makes sense to add an `install` command.

> I was about to say that CI/CD seems beyond the first 48 hours, but I think that might be a shortcoming and an opportunity for enhancement. I hadn’t thought of it. Maybe we could tie it in with a get started guide or learn pathway.

I agree, it should probably be a part of a learn pathway. 👍

**Comment by RobbieMcKinstry** [comment]
Thank you Cobraz! I appreciate your feedback :)

**Comment by RobbieMcKinstry** [comment]
Related to https://github.com/pulumi/actions/issues/789

**Comment by ringods** [comment]
@RobbieMcKinstry @abhinav If the install-only workflow gets supported in `pulumi/actions` by way of #834, please follow up with the following actions:

* [ ] Add an official deprecation message to [pulumi/setup-pulumi/README.md](https://github.com/pulumi/setup-pulumi/blob/master/README.md)
* [ ] Remove `pulumi/setup-pulumi` from the [Github Actions Marketplace.](https://github.com/marketplace/actions/setup-pulumi-cli) See the section [Removing an action from GitHub Marketplace](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace#removing-an-action-from-github-marketplace) in the Github docs on how to do that. 

I expect removing the listing from the Marketplace has no implication on working setups as actions are retrieved from the Github repository, not via the Marketplace.

**Comment by abhinav** [comment]
Reopening for follow-up items^

**Comment by abhinav** [comment]
Added a deprecation notice to the readme https://github.com/pulumi/setup-pulumi/pull/42
and removed all published versions of setup-pulumi from GitHub Marketplace.

<img width="422" alt="image" src="https://user-images.githubusercontent.com/41730/224090775-692c9c86-c11e-44ec-89a4-8c53cc49b933.png">


Existing users will still be able to use it but it won't be discoverable anymore.
Closing
