### ISSUE TITLE
Add option to pass default organization

### ISSUE THREAD

**Issue by mat-machado** [pulumi/actions#692]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Hey Everyone!

I would like to know if it is possible to add an option to select which organization will be used to run the command, either `up` or `preview`.
Currently the alternative is to run it via shell, installing Pulumi and then running the command `pulumi org set-default <organization>`.
I would like to know if it is possible to add this feature.

### Affected area/feature
- CI

**Comment by RobbieMcKinstry** [comment]
Hi Mat. A theme of the open issues for this repo is "not enough support for the subcommands" users want, resulting in exactly the scenario you're describing: having to run the CLI separately for specific needs. Personally, I don't think it would be unreasonable to support this command.

Could you give me a little more detail about your setup? My understanding was that typically the stack name is used to indicate organization membership. Are your stacks not named in the format`MyOrganization/MyProject/MyStack`, or are you unable to use this format when passing the stack name? Are you deploying one Project to multiple organizations?

**Comment by mat-machado** [comment]
Hi Robbie, thanks for the reply!

Due to your answer, I wonder about the method we create our stacks. Currently we only pass the "dev" or "prod" stack, we do not pass the organization together.

I will run some tests here but I believe this will solve the problem. Thank you very much!

**Comment by RobbieMcKinstry** [comment]
Thanks for following up, Mateus! Best of luck with the new stack names! :)
