### ISSUE TITLE
Add workaround for ADAL deprecation message emitted by azure CLI in action image

### ISSUE THREAD

**Issue by viveklak** [pulumi/actions#710]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Azure native currently relies on go-autorest which uses an auth library that uses the local azure CLI to handle auth. As discussed in https://github.com/pulumi/pulumi-azure-native/discussions/1565, recent versions of az cli have added a deprecation message which throws off the underlying auth library causing failures for users. While users can control the AZ CLI version in their local environments, the Pulumi GH action runs into this issue as well. While we are awaiting a move away from the underlying auth library  - tracked in https://github.com/pulumi/pulumi-azure-native/issues/1566, it would be great if the GH action would embed one of the following workarounds:
1. Pin the az CLI to 2.33.1
2. Set the following global config for az CLI: `az config set core.only_show_errors=true`

**Comment by viveklak** [comment]
cc @RobbieMcKinstry

**Comment by RobbieMcKinstry** [comment]
Hi @viveklak 
I'm a little foggy on the ask. AFAIK this GitHub action uses the AZ CLI. I'm not seeing it in `package.json`.

Is the problem downstream of the action itself? _i.e._ users of AZ Native will hit this issue, but there's nothing in this repository relating directly to the issue; users just need the environment in which this action is running to have the AZ CLI configured differently.

**Comment by viveklak** [comment]
@RobbieMcKinstry Apologies. I was under the impression the GH action was using the kitcken sink docker image but it was updated to be a native GH action a long time ago. This is something the user can control in the image they invoke the action from. I will close this and open a corresponding issue in https://github.com/pulumi/pulumi-docker-containers instead since that is potentially problematic for users on other CI/CD platforms.

**Comment by viveklak** [comment]
Issue on docker container here: https://github.com/pulumi/pulumi-docker-containers/issues/106
