### ISSUE TITLE
pulumi output are not display during pulumi up

### ISSUE THREAD

**Issue by alexandre-girard-maif** [pulumi/actions#731]
### What happened?

During the pulumi up action, if there is no resources to modify there is nothing display

### Steps to reproduce

1. Launch `pulumi up` when no resources are require modifications.

### Expected Behavior

![pulumi_up-3 18 1](https://user-images.githubusercontent.com/77633105/192537828-5abfa2f2-7a24-4e9c-96e5-f53a3de3759c.png)

### Actual Behavior

![pulumi_up-3 19 1](https://user-images.githubusercontent.com/77633105/192537888-2ddd4af2-b1fd-4ae2-91b2-e9c1aeb78888.png)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by haoguo-wdc** [comment]
I think the problem might be bigger than the issue subject suggested.
I don't see output even with resource diffs.

![image](https://user-images.githubusercontent.com/98858887/192823240-6e705c3e-e8af-4dc2-9622-94fb425a9ac7.png)

![image](https://user-images.githubusercontent.com/98858887/192823375-0138dbbf-4343-41bf-993b-8a7a79ee72c7.png)

**Comment by alexandre-girard-maif** [comment]
hi Hao,

just by curiosity, what's happen if you use the action with fix version 3.18.1 ?

**Comment by haoguo-wdc** [comment]
@alexandre-girard-maif 
3.18.1 works as expected
![image](https://user-images.githubusercontent.com/98858887/192837608-c1796ded-1f60-4054-ae24-2e1c445fe868.png)
compare to v3
![image](https://user-images.githubusercontent.com/98858887/192837880-e7073c7e-9643-4ad4-b6ab-3f676005f67c.png)

**Comment by alexandre-girard-maif** [comment]
ok, so I will edit the title to explain it's not only when no change

**Comment by tlinhart** [comment]
I'm experiencing the same issue, tried to [ask on Slack](https://pulumi-community.slack.com/archives/C84L4E3N1/p1664184654465199) but no response.

**Comment by RobbieMcKinstry** [comment]
Hey all, sorry for the slow movement on this. I've been out with COVID for a while now, and the end of the quarter tore me away from triage duty. I will carve out some time this week to look into this.

v3.19.1 was a pretty modest upgrade so it's likely this bug won't take much snoof out and fix. I'm going to prioritize this over new features since it seems like this is impacting a number of users.

**Comment by RobbieMcKinstry** [comment]
Just to follow up here, since users are reporting this bug is unique to v3.19.1, I bet the bug was introduced in https://github.com/pulumi/actions/pull/719. I haven't had a chance to build a repro yet, which is what I'll do now.

Nevertheless, separately, we took a stab at fixing it in https://github.com/pulumi/actions/pull/746 but if the bug originates in #719 I suspect that won't do the trick.

**Comment by DeanShackleyNewDay** [comment]
Hi Robbie, I have just retested and v3.19.1 breaks it for us as well.   Previously we had just been through the release history and guessed it might have been the color output change that broke it.  Nothing more than that, sorry can't be of more help on this.

**Comment by RobbieMcKinstry** [comment]
No worries, thanks for the reply! :)

**Comment by cobraz** [comment]
Interesting ... When my stack fails, it shows the output. When it succeeds, it does not.

🚫 Build that failed:

![Skjermbilde 2022-10-18 kl  20 13 11](https://user-images.githubusercontent.com/3726815/196511235-1faa8666-c3fd-4dc2-81f3-a48a0fb33d7d.jpg)

✅ Build that succeeded:

![Skjermbilde 2022-10-18 kl  20 13 52](https://user-images.githubusercontent.com/3726815/196511392-5a3379e8-c9f9-457f-a33a-d166e89f8ae2.jpg)

Might be random … ?

**Comment by RobbieMcKinstry** [comment]
@cobraz are those warnings something we should be wary of? 😅

**Comment by cobraz** [comment]
> @cobraz are those warnings something we should be wary of? 😅 

Yeah, we should probably look into that 😅

**Comment by johnkors** [comment]
Subscribe.

**Comment by RobbieMcKinstry** [comment]
Anyone: please feel free to reopen this issue if the fix in #746 does not solve the issue for you. The next scheduled minor release is Dec 1, but I'll try to cut a release before then to release this patch.
