### ISSUE TITLE
Node.js 12 runtime for GH actions is deprecated

### ISSUE THREAD

**Issue by praneetloke** [pulumi/actions#750]
### What happened?

GitHub has deprecated the Node.js 12 runtime and recommends upgrading actions to v16 runtime.

### Steps to reproduce

Run any workflow with the `pulumi/actions` step.

### Expected Behavior

No deprecation warning is produced.

### Actual Behavior

The following warning is produced on the workflow job:

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: pulumi/actions
```

<details>

<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/1466314/194906101-0d61753d-5451-43b0-9664-68694deacd8f.png)

</details>

### Additional context

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment]
Hi @praneetloke 
I think our hands are bound until December since that's when the last version of GH Enterprise that doesn't support Node 16 falls sunsets.
I tried to clarify that in the [README](https://github.com/pulumi/actions#node-12-support-ending-2022-12-07) but maybe I should pin an issue as well. What do you think?

**Comment by praneetloke** [comment]
> I tried to clarify that in the [README](https://github.com/pulumi/actions#node-12-support-ending-2022-12-07) but maybe I should pin an issue as well. What do you think?

@RobbieMcKinstry ah I missed that in the README. Thanks for sharing that. I did, however, notice your comment in the `action.yml`. Having a pinned issue would be good since it seems GHA is surfacing the deprecation in every workflow run now (if they weren't before.)

**Comment by RobbieMcKinstry** [comment]
Sweet! If you don't mind, I will update this issue with the relevant context and pin it since it gets to the heart of the issue 👍🏻 Sorry, I should have done this without needing to be prompted! :D

**Comment by RobbieMcKinstry** [comment]
Hi again. I lied on accident: I [opened a new issue](https://github.com/pulumi/actions/issues/752) to pin instead of repurposing this one so I could use the first-person voice. Thanks again, Praneet!

**Comment by praneetloke** [comment]
@RobbieMcKinstry all good! Your issue documents this way more thoroughly than this one. Thank you!
