### ISSUE TITLE
Pulumi up action on version later than 3.17.0 does not output to console using dotnet 

### ISSUE THREAD

**Issue by DeanShackleyNewDay** [pulumi/actions#760]
### What happened?

Hey, when we try and use this after version version v3.17.0 we get no output logged via github actions workflow. We are using pulumi with dotnet. We have tried to set the color option to always, never, and raw but no difference. We just seem to get empty lines. It seems like only the up command is affected as our previews have logs. If we tag version v.3.17.0 we see logs. Can you advise please?

### Steps to reproduce

Use dotnet pulumi up via an action after 3.17.0

### Expected Behavior

Logs to console 

### Actual Behavior

Just looks like empty lines with no text

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by DeanShackleyNewDay** [comment]
Duplicate of https://github.com/pulumi/actions/issues/731

**Comment by RobbieMcKinstry** [comment]
@DeanShackleyNewDay Thanks for finding the dup! :) I could have sworn I replied to this issue earlier today... dang! :(

I wanted to ask, what makes you think the bug is related to the color output? I don't have a lead on #731 yet so maybe you've got a lead for me :)

**Comment by RobbieMcKinstry** [comment]
If you could, would you mind answering in the comments of #731? Thank you :D
