### ISSUE TITLE
Using GITHUB_STEP_SUMMARY

### ISSUE THREAD

**Issue by simenandre** [pulumi/actions#761]
Github has launched a way to make steps in Github Actions prettier:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-4

We probably want to use that! :)

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

**Comment by RobbieMcKinstry** [comment]
✨ Love it! ✨ I've got to subscript to the GitHub newsletter or something so I can see these announcements when they come out 🤩

**Comment by koozz** [comment]
I would like to contribute this.
