### ISSUE TITLE
Optimization: Skip Download Pulumi CLI when already present

### ISSUE THREAD

**Issue by RobbieMcKinstry** [pulumi/actions#789]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

With the exception of MacOS and self-hosted runners, Pulumi comes installed on GitHub Actions runners by default. Right now, when a user does not specify a specific version of Pulumi to use, this action defaults to `latest`. Instead, we should use whatever version of Pulumi is installed on the runner, if one exists. This will remove the need to re-download Pulumi for the vast majority of users (anyone who is using Windows or Ubuntu runners).

As described in https://github.com/pulumi/actions/issues/787, this would eliminate `~100MBs` of network traffic. And, detailed in https://github.com/pulumi/actions/issues/674, it would allow the action to be used in the context of where outbound traffic is blocked.

### Affected area/feature

[The `downloadCli` function.](https://github.com/pulumi/actions/blob/master/src/libs/pulumi-cli.ts#L34)

**Comment by ehafenmaier** [comment]
I'm interested in helping with this issue.

**Comment by RobbieMcKinstry** [comment]
Awesome! Thanks @ehafenmaier! Let me know if you need any input :)

**Comment by ehafenmaier** [comment]
@RobbieMcKinstry I do have few questions based on this issue being mentioned in #674:

- Can we assume a specific Pulumi CLI version was not requested if the range parameter is `^3`?
- Can the `isAvailable()` function be used to check if the Pulumi CLI exists on the runner?  (It seems like that function was created for this scenario)
- If both of the above are `true` then should we just exit the `downloadCli()` function right before `getVersionObject()` is called so the outbound network call is skipped as well?  (Logging to the console that the download was skipped and the runner CLI will be used)

**Comment by RobbieMcKinstry** [comment]
I will answer your second and third questions first because they're easier! 😅 

> Can the isAvailable() function be used to check if the Pulumi CLI exists on the runner? (It seems like that function was created for this scenario)

Yes! Very convenient that already exists! ;D It's a little gnarly, so it might be wise to verify it works as expected.

> f both of the above are true then should we just exit the downloadCli() function right before getVersionObject() is called so the outbound network call is skipped as well? (Logging to the console that the download was skipped and the runner CLI will be used)

Exactly! Bingo!

-------

> Can we assume a specific Pulumi CLI version was not requested if the range parameter is ^3?

The behavior we need is slightly more complex. I think the workflow looks like this:

1. Check if pulumi is installed using `isAvailable()`
2. If it's **NOT** installed, then we have to proceed as normal.
3. If it is installed, we need to check whether version is compatible with the version specified in the `pulumi-version` parameter.

Step 3 will require parsing the stdout of `pulumi version` and checking the compatibility. I believe the `semver.satisfies()` function will work for this.

If it's easier to rewrite `isAvailable(): Promise<bool>` to a function like `getVersion(): Promise<string?>`, usually essentially the same shell command, but returning `stdout` if `stderr === ""`

Does that make sense? I'm sorry if my explanation is a confusing.

Thanks very much for your assistance! <3

**Comment by ehafenmaier** [comment]
Clear as mud @RobbieMcKinstry 😜 

In all seriousness, your explanation makes perfect sense. I'm happy to see my approach wasn't too far off the mark. I'm pretty sure I have enough to proceed. 

Thanks again for the input!
