### ISSUE TITLE
Support command flag --policy-pack and --policy-pack-config

### ISSUE THREAD

**Issue by eduardofesilva** [pulumi/actions#827]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Current Pulumi action does not support the addition of the following flags as Pulumi options
* `--policy-pack`
* `--policy-pack-config`

### Affected area/feature
Pulumi Github action

**Comment by RobbieMcKinstry** [comment]
Thanks for this suggestion!

**Comment by MitchellGerdisch** [comment]
They are available via the `policyPacks` and `policyPackConfigs` inputs
https://github.com/pulumi/actions/blob/50c6cb368f40038cfed01b92e39b836aec3cf3f4/action.yml#L66

But they should probably be named in line with the other properties such as `expect-no-changes`

**Comment by RobbieMcKinstry** [comment]
Yes, just noticing now that they aren't documented!

**Comment by eduardofesilva** [comment]
Thank you @MitchellGerdisch for the finding. I will try it out
@RobbieMcKinstry should I close this issue or use it as an issue to improve the current docs about this feature available?

**Comment by RobbieMcKinstry** [comment]
Thanks for asking; please leave this open for now :D I'm going to use this issue to track the docs change early next week.

**Comment by RobbieMcKinstry** [comment]
Closed by https://github.com/pulumi/actions/pull/842
