### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by ffMathy** [pulumi/actions#83]
The documentation on Pulumi's website for GitHub Actions uses `v1` of the action.

In addition, the "Getting started" sample of this repo doesn't work, since the `v2` of the action is not present (the branch does not exist).

**Comment by stack72** [comment]
Hi @ffMathy 

We are in the process of releasing this action right now! You are maybe 1 hour ahead of us :)

Paul

**Comment by ffMathy** [comment]
Oh wow, bad timing then. This is the first time I've used Pulumi GitHub Actions 😆

**Comment by ffMathy** [comment]
Crazy coincidence.

**Comment by stack72** [comment]
You will be able to look in the .github/workflows for a few sample workflows!

I'm even writing the blog post as we speak :)

**Comment by stack72** [comment]
Hi @ffMathy 

Closing this out as pulumi/actions@v2 is now available

Sorry about that cut over :/

Paul
