### ISSUE TITLE
Dotnet workflow is failing

### ISSUE THREAD

**Issue by cobraz** [pulumi/actions#904]
### What happened?

Dotnet is failing tests, seems to have some outdated dependencies.

### Expected Behavior

Jobs should complete

### Steps to reproduce

see https://github.com/pulumi/actions/actions/runs/4649654940

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by cobraz** [comment]
@RobbieMcKinstry, something you wanna take a stab at?

**Comment by ehafenmaier** [comment]
@cobraz @RobbieMcKinstry 

The errors displayed in the workflow jobs show that Pulumi.Random is not compatible with .NET Core 3.1. I upgraded the test stack project and workflow job to use .NET 6.x, which is the current LTS version.

PR #907

**Comment by cobraz** [comment]
Thank you, @ehafenmaier 🙏

Closing this 👍
