### ISSUE TITLE
v2 Action does not honor command parameters

### ISSUE THREAD

**Issue by jeffrichie** [pulumi/actions#91]
New v2 Action does not honor parameters via `command: `

## Expected behavior
Honor my command line parameters.

## Current behavior
Just runs `pulumi up`

## Steps to reproduce

1. Setup basic Actions workflow with v2 of Pulumi Action
2. Try to pass `command: up --config-file <different config>`
3. Notice that config file is not read from

**Comment by cobraz** [comment]
Hi! Thanks you for opening this issue. This is a known limitation at the moment. We're tracking this in #88. Closing this for now :)
