### ISSUE TITLE
Add option to always install latest available `pulumi`

### ISSUE THREAD

**Issue by kmosher** [pulumi/actions#934]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently [the action will use the runner installed pulumi version](https://github.com/pulumi/actions/blob/fbefaab4256dcab040fac3de15ab2a761ae86615/src/libs/pulumi-cli.ts#L56) if it's "good enough" to match the version string supplied. This leaves the ability to upgrade to a specific new version of `pulumi`, but given Pulumi's release cadence, if you wanted to stay on bleeding edge, you'd have to update your actions constantly.

For those of us who want to dogfood to the max, it'd be nice to be able to specify `pulumi-version` as `latest` or have an option like `always-upgrad-cli` that upgrades to the highest possible version allowed by the semver string in `pulumi-version`.

**Comment by Frassle** [comment]
I think the "pulumi-version" option is just a string so we could just allow "latest" or a semver range there (continuing to default to "^3" when unset)

**Comment by RobbieMcKinstry** [comment]
Linking in this conversation from earlier today about the same thing:
https://github.com/pulumi/actions/issues/933#issuecomment-1542671230

**Comment by danielrbradley** [comment]
Bumping this again - we've recently got caught out by only pinning to the default version range (`^3`) but not actually getting the latest version. I'd also like to see a `latest` option which queries https://www.pulumi.com/latest-version
